services:
  - type: web
    name: campusfound
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings_prod
      - key: DATABASE_URL
        fromDatabase:
          name: campusfound-db
          property: connectionString

databases:
  - name: campusfound-db
    plan: free
    databaseName: campusfound
    user: campusfound